services:
  - type: web
    name: inkflow-api
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/inkflow-backend-1.0.0.jar
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false